### ISSUE TITLE
Update the func.yaml File Reference to include Default and Range values

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/docs#106]
The following file should document all the possible values in the `func.yaml` file:
https://github.com/fnproject/docs/blob/master/fn/develop/func-file.md

However, the file does not document default, maximum, or the valid range of values for an attribute. Where relevant, the file should be updated to include these values.

**Comment by angelica-viorato** [comment]
PR: https://github.com/fnproject/docs/pull/116

**Comment by angelica-viorato** [comment]
PR: #116
