### ISSUE TITLE
Update Troubleshooting docs to mention printing to stderr

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/docs#108]
Update troubleshooting guides to show how to print to stderr.

For example in python:
`print(“start processing in handler simple example stderr”, file=sys.stderr)`

Update both docs and tutorial (https://github.com/fnproject/tutorials/blob/master/Troubleshooting/README.md)

**Comment by angelica-viorato** [comment]
PR: https://github.com/fnproject/tutorials/pull/196
