### ISSUE TITLE
Hard to find the troubleshooting pages e.g. for the runc issue

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/docs#118]
Mike,

It took me quite some time to find this page .. 
https://github.com/fnproject/docs/blob/master/fn/troubleshoot/known-issues/2019-08-fn-invoke-fails.md

Maybe we should have a troubleshooting hyperlink to the troubleshoot/known-issues pages?

**Comment by michael-w-williams** [comment]
Thanks Sachin. Its on my to-do list. I'll add it to the front page. Will also link to the tutorial. Also planning on putting some of tutorial info (DEBUG) in the docs repo. The cross linking should help improve search results.

**Comment by michael-w-williams** [comment]
Fixed with PR: https://github.com/fnproject/docs/pull/122
