### ISSUE TITLE
Fn: 'log' is not a Fn Command

### ISSUE THREAD

**Issue by Arvinzhu** [fnproject/docs#120]
I had read the command document file. But two questions haunts me:  
1. `This command gets a 'call', 'configuration' or 'log' to retrieve information for an object ('app' or 'function').`
 In this desciption, this command gets a 'call', 'configuration' or 'log',but when I run `fn get log appname`
this result is  `Fn: 'log' is not a Fn Command `

```
[root@node100 fn]# fn get --help
  fn get -   Get an object to retrieve its information
                            
USAGE
  fn [global options] get [command options] <subcommand>
    
DESCRIPTION
  This command gets a 'call', 'configuration' or 'log' to retrieve information for an object ('app' or 'function').
    
SUBCOMMANDS
  config, config, cf      Get configurations for apps and functions
  help, h                 Shows a list of commands or help for one command
                      
COMMAND OPTIONS
  --help, -h  show help

FURTHER HELP:  See 'fn get <subcommand> --help' for more information about a command.
```

2.  Who can tell me how to get the runtime log of apps and functions   ?

**Comment by michael-w-williams** [comment]
@Arvinzhu Good catch on (1). I'll open a PR to fix this against the CLI. Then close this issue.  For (2), how logs work with Fn are covered here: https://github.com/fnproject/tutorials/tree/master/Troubleshooting#logs

**Comment by michael-w-williams** [comment]
@Arvinzhu You can track the fix here: https://github.com/fnproject/cli/issues/600. Thanks again.
