### ISSUE TITLE
fn config route is not an fn command

### ISSUE THREAD

**Issue by dukescript** [fnproject/docs#48]
The doc for config, which is linked from the main Readme should be current, but isn't:

3. Route level configuration
fn  config route myapp hello2 LOG_LEVEL info

"route" is no longer supported in v2 and will not work

Here's the file I'm referring to:
https://github.com/fnproject/docs/blob/master/fn/develop/configs.md

**Comment by michael-w-williams** [comment]
This reference has been removed. Any other incorrect "route" references will be removed as well. Tracked by this issue: https://github.com/fnproject/docs/issues/89
