### ISSUE TITLE
Add "brew update" before installing the CLI

### ISSUE THREAD

**Issue by denismakogon** [fnproject/docs#54]
Follow up of https://github.com/fnproject/cli/issues/549, there's a need to update the local package index before installing the CLI because it may give a feeling that Fn CLI releases are outdated.

**Comment by michael-w-williams** [comment]
Addressing with the following issues and PRs:

* Tutorial Issue: https://github.com/fnproject/tutorials/issues/163
* Tutorial PR: https://github.com/fnproject/tutorials/pull/192

**Comment by michael-w-williams** [comment]
Fixed this issue with following PRs:
* Main Fn repo: https://github.com/fnproject/fn/pull/1547
* Tutorials repo: https://github.com/fnproject/tutorials/pull/192

Also closing tutorials issue: https://github.com/fnproject/tutorials/issues/163
