### ISSUE TITLE
Add Example: Set configuration values that become Environment Variables

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/docs#91]
Add an example showing how setting configuration values in the Fn context can be used as environment variables in an Fn Docker container.

* Example can be based on <https://github.com/abhirockzz/fn-oracledb-atp-sample>
* Also examples in different programming languages. (go, node, python, Java)

**Comment by angelica-viorato** [comment]
Please see: https://github.com/fnproject/docs/pull/103

**Comment by angelica-viorato** [comment]
Done: https://github.com/fnproject/docs/issues/91
