### ISSUE TITLE
Update QR Code Example to produce well-formed png file

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/docs#95]
The FDK-Java QR Code example has been updated for the latest Fn and Java versions. See: <https://github.com/fnproject/docs/blob/master/fdks/fdk-java/examples/qr-code/README.md>

However, the .png file output from the service is not well-formed. You get a 47 byte file that is not recognized as a .png. Someone needs to troubleshoot the code and see what's up.

**Comment by angelica-viorato** [comment]
Hi Mike, 

Please could you try again this function? I just did it and the png file with the QR was created. I didn't change anything.

Let me know what happens

**Comment by michael-w-williams** [comment]
I was able to confirm what Angie found. If you pass the example the correct parameters, it works. However if you don't, the Function crashes with a 502 Gateway error. 

The source code it throwing a RunTimeException if any data is passed in an incorrect format. This  of course causes the function to exit with no response.

I will update the code and example to support triggers and fix it early next week.

**Comment by michael-w-williams** [comment]
Fixed with PR: https://github.com/fnproject/docs/pull/115. Problem we were having was with curl not Fn.
