### ISSUE TITLE
Update Async Thumbnails example to produce an output

### ISSUE THREAD

**Issue by angelica-viorato** [fnproject/docs#96]
The FDK-Java Async Thumbnails example has been updated for the latest Fn and Java versions. 
https://github.com/fnproject/docs/blob/angie-javaex1/fdks/fdk-java/examples/async-thumbnails/README.md

However, it is not creating any output or error. Someone needs to troubleshoot the code and see what's going on.

**Comment by michael-w-williams** [comment]
Code is on this Branch: https://github.com/fnproject/docs/tree/angie-javaex1

**Comment by angelica-viorato** [comment]
I have updated the pom.xml file with a dependency required for the testcases.  

Also I ran this code again but this time using curl-v option and it showed  a 502 Bad gateway error. Nothing is created in the minIO page (no images or repository) .

**Comment by michael-w-williams** [comment]
Ok. Do you want me to take a look?  I can after I wrap up the tutorials I'm working on.

**Comment by angelica-viorato** [comment]
Yes please. I couldn't find anything wrong in the code.

**Comment by angelica-viorato** [comment]
I found these error messages in the logs:

convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560.
convert-im6.q16: no images defined `-' @ error/convert.c/ConvertImageCommand/3258.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560.
convert-im6.q16: no images defined `-' @ error/convert.c/ConvertImageCommand/3258.
convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560.
convert-im6.q16: no images defined `-' @ error/convert.c/ConvertImageCommand/3258. 

Seems that the issue is with the installation of the ImageMagick tool

**Comment by michael-w-williams** [comment]
We are deferring any further updates for the FDK for Java Async Thumbnail example found here: https://github.com/fnproject/docs/tree/master/fdks/fdk-java/examples/async-thumbnails

After uploading the test image to the application nothing happens. Likely this is an issue with the Flow server. However, we do not know for sure. Given the amount of effort required to debug and troubleshoot this example, we are deferring further work until Fn Flow server is updated. We can revisit this example then.

**Comment by michael-w-williams** [comment]
Closing deferred issue. Reopen when works starts on this issue again.
